//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace univercity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_official
    {
        public int code_official { get; set; }
        public string official_show { get; set; }
    }
}
